### PR TITLE
Pullup

### LINKED ISSUE #279: All backends but legion are broken refactored master

### LINKED ISSUE #280: Master-Refactor merge aftermath
- [ ] flecsi-sp broken: laristra/flecsi-sp#9
- [ ] only legion backend works: #279
- [x] `Werror` clang builds broken: #278 
- [x] 8 tests fail on Travis: #269

### LINKED ISSUE #306: MPI backend is broken again
See here: https://travis-ci.org/laristra/flecsi/builds/261404084

### PR DESCRIPTION
**Pull request by ipdemes**
Fix #279 
Fix #280 
Fix #306

### CODE REVIEW

File: flecsi/topology/common/array_buffer.h [hunk 1]
```diff
@@ -0,0 +1,255 @@
...
+  using type = S*;
+};
+
+template<size_t M, class E>
+struct array_buf_ref_type__<domain_entity<M, E>>{
+  using type = E*;
+};
+
+template<typename T, bool B>
+struct array_buf_ref_get__{
```
Comment (flecsibot) [inline flecsi/topology/common/array_buffer.h]: MAJOR Promote this "struct" to a "class" or remove its member functions. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1771)

File: flecsi/topology/common/array_buffer.h [hunk 2]
```diff
@@ -0,0 +1,255 @@
...
+  end()
+  const
+  {
+    return buf_ + size_;
+  }
+
+  template<
+    typename ... Args
+  >
+  void insert(Args && ... args){}
```
Comment (flecsibot) [inline flecsi/topology/common/array_buffer.h]: CRITICAL Add a nested comment explaining why this method is empty, or complete the implementation. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1186)

File: flecsi/topology/common/array_buffer.h [hunk 3]
```diff
@@ -0,0 +1,255 @@
...
+
+template<typename T, bool B>
+struct array_buf_ref_get__{
+  static T get(T a, size_t i){
+    return &a[i];
+  }
+};
+
+template<typename T>
+struct array_buf_ref_get__<T, false>{
```
Comment (flecsibot) [inline flecsi/topology/common/array_buffer.h]: MAJOR Promote this "struct" to a "class" or remove its member functions. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1771)

File: flecsi/data/storage.h [hunk 4]
```diff
@@ -29,6 +38,96 @@ template<
...
+
+  bool
+  register_field(
+    size_t client_key,
+    size_t key,
+    const field_registration_function_t & callback
+  )
+  {
+    if(field_registry_.find(client_key) != field_registry_.end()) {
+      if(field_registry_[client_key].find(key) !=
```
Comment (flecsibot) [inline flecsi/data/storage.h]: MAJOR Merge this if statement with the enclosing one. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1066)

File: flecsi/execution/context.h [hunk 5]
```diff
@@ -53,6 +54,85 @@ struct context__ : public CONTEXT_POLICY
...
+    size_t KEY
+  >
+  bool
+  register_function(
+  )
+  {
+    clog_assert(function_registry_.find(KEY) == function_registry_.end(),
+                "function has already been registered");
+
+    const std::size_t addr = reinterpret_cast<std::size_t>(FUNCTION);
```
Comment (flecsibot) [inline flecsi/execution/context.h]: MAJOR Replace "reinterpret_cast" with a safer cast. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS3630)

File: flecsi/execution/context.h [hunk 6]
```diff
@@ -53,6 +54,85 @@ struct context__ : public CONTEXT_POLICY
...
+    clog(info) << "Registering function: " << addr << std::endl;
+
+    function_registry_[KEY] =
+      reinterpret_cast<void *>(FUNCTION);
```
Comment (flecsibot) [inline flecsi/execution/context.h]: MAJOR Replace "reinterpret_cast" with a safer cast. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS3630)

File: flecsi/data/common/registration_wrapper.h [hunk 7]
```diff
@@ -236,14 +253,14 @@ struct client_registration_wrapper__<
         utils::const_string_t("__flecsi_internal_adjacency_index__").hash(),
         INDEX_TYPE::value
       >();
-
+      int ispace = INDEX_TYPE::value;
```
Comment (flecsibot) [inline flecsi/data/common/registration_wrapper.h]: MINOR Remove this unused "ispace" local variable. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1481)

File: flecsi/data/common/registration_wrapper.h [hunk 8]
```diff
@@ -313,7 +330,7 @@ struct client_registration_wrapper__<
         utils::const_string_t("__flecsi_internal_field_hash_base__").hash(),
         INDEX_TYPE::value
       >();
-
+      int ispace = INDEX_TYPE::value;
```
Comment (flecsibot) [inline flecsi/data/common/registration_wrapper.h]: MINOR Remove this unused "ispace" local variable. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS1481)

**Comment by ollielo** [comment]
There are basic two kinds of error in the Travis. The first one is the execution of `reduction` failed for Legion backend. However, It did not fail for all the test configurations and I can't see any pattern there. @ipdemes Is there still some bug in the implementation of Legion reduction?

The other one is the -Werror of [create_entity()](https://github.com/laristra/flecsi/blob/dd37be963631a5d97933b76e75fc3bb2d82f3d5f/flecsi/supplemental/mesh/test_mesh_2d.h#L118) in test_mesh_2d.h. The body of the function is comment out with `#if 0...#endif` and Clang++ is complaining about control reaching the end of the function without return a value. @tuxfan , why did you commented it out in the first place?

**Comment by ollielo** [comment]
@ipdemes ,

Should we fix Legion reduction before or after merging this PR?

**Comment by ipdemes** [comment]
@ollielo I would say after. For now I will just mark this test as NOCI (it is NOCI in the master branch)

**Comment by ipdemes** [comment]
@ollielo I think we can merge the branch now. all Travis builds pass except the ones where we use clang + Werror=ON. @tuxfan , what do you think?

**Comment by ollielo** [comment]
@nickm319 

O.K. I got it.

**Comment by ollielo** [comment]
@ipdemes 

I think we can go ahead and merge it.

**Comment by charest** [comment]
I tried it out.  It doesnt break any of the legion stuff at least.  So I merged it.

**Comment by ipdemes** [comment]
@charest great!
