### PR TITLE
fix some clang warnings

### LINKED ISSUE #278: Fix clang warnings in refactored master

### PR DESCRIPTION
**Pull request by junghans**
Fix #278

Also see laristra/cinch#98

### CODE REVIEW

**Comment by junghans** [comment]
@staleyLANL: there is still one warning left:
```
[ 76%] Building CXX object flecsi/execution/CMakeFiles/simple_task.dir/test/simple_task.cc.o
cd /home/flecsi/flecsi/build/flecsi/execution && /usr/lib64/ccache/clang++  -DCINCH_OVERRIDE_DEFAULT_INITIALIZATION_DRIVER -DCLOG_COLOR_OUTPUT -DCLOG_STRIP_LEVEL=3 -DCLOG_TURNSTILE_NWAY=1 -DDEBUG -DENABLE_COLORING -DENABLE_LEGION_TLS -DENABLE_METIS -DENABLE_MPI -DENABLE_PARMETIS -DFLECSI_DBC_THROW -DFLECSI_REQUIRE_ON -DHAVE_EXODUS -DLEGION_CMAKE -DMAPPER_COMPACTION -I/home/flecsi/flecsi -I/home/flecsi/flecsi/build -I/home/flecsi/flecsi/cinch/boost/preprocessor/include -I/usr/include/openmpi-x86_64 -I/home/flecsi/flecsi/cinch/logging -I/usr/local/include -I/usr/local/include/legion -I/usr/local/include/realm -I/usr/local/include/mappers -I/home/flecsi/flecsi/flecsi -I/home/flecsi/flecsi/build/flecsi -I/home/flecsi/flecsi/flecsi/.. -I/home/flecsi/flecsi/build/flecsi/.. -I/home/flecsi/flecsi/cinch/gtest/googlemock/include -I/home/flecsi/flecsi/cinch/gtest/googletest -I/home/flecsi/flecsi/cinch/gtest/googletest/include -I/home/flecsi/flecsi/cinch/auxiliary -I/home/flecsi/flecsi/build/test/execution  -Wno-deprecated-declarations -std=c++14 -g   -DOMPI_SKIP_MPICXX -DMPICH_SKIP_MPICXX -o CMakeFiles/simple_task.dir/test/simple_task.cc.o -c /home/flecsi/flecsi/flecsi/execution/test/simple_task.cc
In file included from /home/flecsi/flecsi/flecsi/execution/test/simple_function.cc:9:
In file included from /home/flecsi/flecsi/flecsi/data/data.h:14:
In file included from /home/flecsi/flecsi/flecsi/data/client.h:16:
In file included from /home/flecsi/flecsi/flecsi/execution/context.h:234:
In file included from /home/flecsi/flecsi/flecsi/flecsi_runtime_context_policy.h:39:
/home/flecsi/flecsi/flecsi/execution/legion/context_policy.h:550:47: warning: address of function 'test_function_tuple_delegate' will always evaluate to 'true' [-Wpointer-bool-conversion]
    clog(info) << "Registering function: " << FUNCTION << std::endl;
                                           ~~ ^~~~~~~~
/home/flecsi/flecsi/flecsi/execution/legion/execution_policy.h:371:43: note: in instantiation of function template specialization 'flecsi::execution::legion_context_policy_t::register_function<double, std::tuple<double, double>, &flecsi::execution::test_function_tuple_delegate, 7959380277541343511>' requested here
    return context_t::instance().template register_function<
                                          ^
/home/flecsi/flecsi/flecsi/execution/function.h:57:39: note: in instantiation of function template specialization 'flecsi::execution::legion_execution_policy_t::register_function<double, std::tuple<double, double>, &flecsi::execution::test_function_tuple_delegate, 7959380277541343511>' requested here
    return EXECUTION_POLICY::template register_function<
                                      ^
/home/flecsi/flecsi/flecsi/execution/legion/context_policy.h:550:47: note: prefix with the address-of operator to silence this warning
    clog(info) << "Registering function: " << FUNCTION << std::endl;
                                              ^
                                              &
1 warning generated.
```
(from https://travis-ci.org/laristra/flecsi/jobs/250563291#L1965)

Maybe you know how to fix that.

**Comment by staleyLANL** [comment]
My first thought would be to try the solution suggested by the warning message: writing &FUNCTION instead of FUNCTION. C++ has an implicit conversion from pointers to bools, which the compiler apparently wants to do in this context. Aren't we wanting to output the address (not a bool) anyway? :-)

**Comment by junghans** [comment]
I did that, but I got:
```
[ 16%] Building CXX object flecsi/execution/CMakeFiles/simple_function.dir/legion/runtime_driver.cc.o
cd /home/flecsi/flecsi/build/flecsi/execution && /usr/lib64/ccache/clang++  -DCINCH_OVERRIDE_DEFAULT_INITIALIZATION_DRIVER -DCLOG_COLOR_OUTPUT -DCLOG_STRIP_LEVEL=3 -DCLOG_TURNSTILE_NWAY=1 -DDEBUG -DENABLE_COLORING -DENABLE_LEGION_TLS -DENABLE_METIS -DENABLE_MPI -DENABLE_PARMETIS -DFLECSI_DBC_THROW -DFLECSI_REQUIRE_ON -DHAVE_EXODUS -DLEGION_CMAKE -DMAPPER_COMPACTION -I/home/flecsi/flecsi -I/home/flecsi/flecsi/build -I/home/flecsi/flecsi/cinch/boost/preprocessor/include -I/usr/include/openmpi-x86_64 -I/home/flecsi/flecsi/cinch/logging -I/usr/local/include -I/usr/local/include/legion -I/usr/local/include/realm -I/usr/local/include/mappers -I/home/flecsi/flecsi/flecsi -I/home/flecsi/flecsi/build/flecsi -I/home/flecsi/flecsi/flecsi/.. -I/home/flecsi/flecsi/build/flecsi/.. -I/home/flecsi/flecsi/cinch/gtest/googlemock/include -I/home/flecsi/flecsi/cinch/gtest/googletest -I/home/flecsi/flecsi/cinch/gtest/googletest/include -I/home/flecsi/flecsi/cinch/auxiliary -I/home/flecsi/flecsi/build/test/execution  -Werror -Wno-deprecated-declarations -std=c++14 -g   -DOMPI_SKIP_MPICXX -DMPICH_SKIP_MPICXX -o CMakeFiles/simple_function.dir/legion/runtime_driver.cc.o -c /home/flecsi/flecsi/flecsi/execution/legion/runtime_driver.cc
In file included from /home/flecsi/flecsi/flecsi/execution/test/simple_function.cc:9:
In file included from /home/flecsi/flecsi/flecsi/data/data.h:14:
In file included from /home/flecsi/flecsi/flecsi/data/client.h:16:
In file included from /home/flecsi/flecsi/flecsi/execution/context.h:234:
In file included from /home/flecsi/flecsi/flecsi/flecsi_runtime_context_policy.h:39:
/home/flecsi/flecsi/flecsi/execution/legion/context_policy.h:550:47: error: cannot take the address of an rvalue of type 'test_function_frt_t (*)(test_function_fat_t)' (aka 'double (*)(tuple<double, double>)')
    clog(info) << "Registering function: " << &(FUNCTION) << std::endl;
                                              ^ ~~~~~~~~
/home/flecsi/flecsi/flecsi/execution/legion/execution_policy.h:371:43: note: in instantiation of function template specialization 'flecsi::execution::legion_context_policy_t::register_function<double, std::tuple<double, double>, &flecsi::execution::test_function_tuple_delegate, 7959380277541343511>' requested here
    return context_t::instance().template register_function<
                                          ^
/home/flecsi/flecsi/flecsi/execution/function.h:57:39: note: in instantiation of function template specialization 'flecsi::execution::legion_execution_policy_t::register_function<double, std::tuple<double, double>, &flecsi::execution::test_function_tuple_delegate, 7959380277541343511>' requested here
    return EXECUTION_POLICY::template register_function<
                                      ^
1 error generated.
make[2]: *** [flecsi/execution/CMakeFiles/simple_function.dir/test/simple_function.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```
(see https://travis-ci.org/laristra/flecsi/builds/250598344#L1075)

**Comment by staleyLANL** [comment]
I'll take a closer look at the cinch code itself; it may be missing something simple (say, stream output of an address) that would clear up the problem. In the meantime, perhaps rather than just &, we could try something like what appears a few lines later: reinterpret_cast<void *>(FUNCTION). Or, the (rvalue) FUNCTION could be placed into a temporary (something like auto tmp_function = FUNCTION;) and &tmp_function sent to clog(info).


--
Martin Staley
CCS-7, Applied Computer Science
Mail Stop B287
Los Alamos National Laboratory
Los Alamos, NM 87545
Phone: 1-505-667-7108

________________________________

**Comment by staleyLANL** [comment]
Reduction:

#include "cinchlog.h"

// register_function
template<typename RETURN, typename ARG_TUPLE, RETURN (*FUNCTION)(ARG_TUPLE)>
bool register_function(void)
{
   clog(info) << "Registering function: " << FUNCTION << std::endl;
   return true;
}

// fun
int fun(std::tuple<float,double>)
{
   return 0;
}

// main
int main(void)
{
   (void)register_function<int,std::tuple<float,double>,fun>();
}

**Comment by staleyLANL** [comment]
I think the solution is going to amount to doing something like this:

     const std::size_t addr = reinterpret_cast<std::size_t>(FUNCTION);
     clog(info) << "Registering function: " << addr << std::endl;

The issue seems to be that FUNCTION isn't a normal function pointer, but a specific, essentially literal value of a function pointer - because it's coming in via a template argument. The error when you write &FUNCTION thus amounts to the error if you try to write something like &100 (Address of the literal value 100 - which makes no sense).

**Comment by staleyLANL** [comment]
Or perhaps just write this:
     std::cout << "Registering function: " << (void *)FUNCTION << std::endl;

File: flecsi/execution/legion/context_policy.h [hunk 1]
```diff
@@ -547,7 +547,8 @@ struct legion_context_policy_t
     clog_assert(function_registry_.find(KEY) == function_registry_.end(),
       "function has already been registered");
 
-    clog(info) << "Registering function: " << FUNCTION << std::endl;
+    const std::size_t addr = reinterpret_cast<std::size_t>(FUNCTION);
```
Comment (flecsibot) [inline flecsi/execution/legion/context_policy.h]: MAJOR Replace "reinterpret_cast" with a safer cast. [rule](https://sonarcloud.io/coding_rules#rule_key=cpp%3AS3630)
